// Content-driven art direction. A profile changes the shader, type behavior,
// transition grammar, ASCII organism, tempo, density, and emotional weather.

export const PROFILES = {
  dmt: {
    id: "dmt",
    sourceName: "DMT",
    label: "DMT",
    index: "01",
    glyph: "◉⃝",
    thesis: "JEWELED MACHINERY / ENTITY-DENSE / LANGUAGE BECOMES ARCHITECTURE",
    subtitle: "The interface learns to speak in radiant tunnels and impossible syntax.",
    shader: "dmt",
    transition: "chrysanthemum",
    tempo: 1.35,
    symmetry: 12,
    palette: ["#ff2eea", "#00f5ff", "#b8ff00", "#ffd400", "#7c4dff"],
    chars: "◉◈◇∆⌬※✦⟡{}[]/\\<>ÆØ",
    ghost: [
      "THE OBJECTS ARE GRAMMAR NOW.",
      "SOMETHING FAST IS BUILDING THE PAGE.",
      "LANGUAGE HAS EXCEEDED ITS CONTAINER.",
    ],
  },
  lsd: {
    id: "lsd",
    sourceName: "LSD",
    label: "LSD",
    index: "02",
    glyph: "⌬",
    thesis: "CRYSTALLINE RECURSION / TRACERS / THOUGHT-LOOP CARTOGRAPHY",
    subtitle: "Every edge remembers where it was. Every sentence has another sentence inside it.",
    shader: "lsd",
    transition: "recursive",
    tempo: 0.72,
    symmetry: 6,
    palette: ["#00e5ff", "#ff4fd8", "#f7ff00", "#795cff", "#ff6b00"],
    chars: "∞∿∴∵≋⟲⟳⌬⋰⋱≈+−×÷",
    ghost: [
      "YOU HAVE READ THIS SENTENCE BEFORE.",
      "THE MARGIN IS LEAVING TRACERS.",
      "A FOOTNOTE IS THINKING ABOUT ITSELF.",
    ],
  },
  salvia: {
    id: "salvia",
    sourceName: "Salvia",
    label: "SALVIA",
    index: "03",
    glyph: "⧉",
    thesis: "ZIPPERED PLANES / CONVEYOR REALITY / THE WHEEL TURNS SIDEWAYS",
    subtitle: "Space is serialized into strips, folded at the edge, and fed to the mechanism.",
    shader: "salvia",
    transition: "zipper",
    tempo: 0.94,
    symmetry: 24,
    palette: ["#ff4500", "#43b3ae", "#b87333", "#b5a642", "#161611"],
    chars: "||||////\\\\====++++⧉⧄⟰⟱",
    ghost: [
      "MIND THE SEAM.",
      "THE PAGE TURNER HAS NOTICED YOUR HAND.",
      "YOU ARE TEMPORARILY TWO-DIMENSIONAL.",
    ],
  },
  dxm: {
    id: "dxm",
    sourceName: "DXM",
    label: "DXM",
    index: "04",
    glyph: "▱",
    thesis: "LOW-FRAME UNREALITY / ROBOTIC DISTANCE / BODY SIGNAL DELAY",
    subtitle: "The scene arrives late, in blocks, from somewhere several feet behind itself.",
    shader: "dxm",
    transition: "desync",
    tempo: 0.34,
    symmetry: 2,
    palette: ["#7097ff", "#e9efff", "#ff4ca8", "#303a66", "#050711"],
    chars: "_—–· .:▱▰▯01ERRNULL",
    ghost: [
      "YOUR CURSOR ARRIVED WITHOUT YOU.",
      "BODY PROCESS: RESPONDING LATE.",
      "THE ROOM IS BUFFERING ITS DISTANCE.",
    ],
  },
  deliriants: {
    id: "deliriants",
    sourceName: "Deliriants",
    label: "DELIRIANTS",
    index: "05",
    glyph: "▓",
    thesis: "ORDINARY BUT WRONG / PHANTOM UI / HOSTILE MEMORY CACHE",
    subtitle: "Nothing looks psychedelic. That is the problem. Do not romanticize the basement.",
    shader: "deliriants",
    transition: "misrecognition",
    tempo: 0.18,
    symmetry: 1,
    palette: ["#c8b853", "#dc143c", "#87908a", "#36454f", "#070706"],
    chars: "...,,,,''`?▓░▒[MISSING]",
    ghost: [
      "THAT BUTTON WAS NOT THERE.",
      "PERIPHERAL PROCESS DETECTED. DO NOT FOLLOW.",
      "MEMORY CHECK FAILED CONVINCINGLY.",
    ],
  },
  "2cb": {
    id: "2cb",
    sourceName: "2CB",
    label: "2C-B",
    index: "06",
    glyph: "❋",
    thesis: "TACTILE COLOR / AESTHETIC RAPTURE / WARM SYNCHRONIZATION",
    subtitle: "The archive becomes touchable light: playful, bodily, ornate, and emotionally permeable.",
    shader: "2cb",
    transition: "pulse",
    tempo: 0.82,
    symmetry: 8,
    palette: ["#ff3d9a", "#ff8a00", "#ffe600", "#00f0c8", "#a66cff"],
    chars: "❋✿✦♡≈∿☼◌◍(){}",
    ghost: [
      "COLOR HAS BECOME A SOCIAL ANIMAL.",
      "THE PAGE IS WARM TO THE TOUCH.",
      "AESTHETIC PROCESS: OPEN.",
    ],
  },
  canon: {
    id: "canon",
    sourceName: "CANON",
    label: "THE CANON",
    index: "00",
    glyph: "⌘",
    thesis: "52 RECURRING SIGNALS / ONE HAUNTED INDEX / NO FINAL THEORY",
    subtitle: "Entities, thresholds, messages, geometries, locations, and emotions cross-contaminate the map.",
    shader: "canon",
    transition: "index",
    tempo: 0.52,
    symmetry: 4,
    palette: ["#00f5ff", "#ff2eea", "#b8ff00", "#ffb000", "#f8f8ff"],
    chars: "ENTLOCGEOTHRMSGEMO:://[]{}⌘",
    ghost: [
      "THE INDEX IS INDEXING YOU BACK.",
      "NO TAXONOMY SURVIVES CONTACT WITH THE THING.",
      "RECORD 53 REFUSES TO EXIST CONSISTENTLY.",
    ],
  },
};

export const PROFILE_ORDER = ["dmt", "lsd", "salvia", "dxm", "deliriants", "2cb", "canon"];

export const SOURCE_TO_PROFILE = Object.fromEntries(
  Object.values(PROFILES).map((profile) => [profile.sourceName.toLowerCase(), profile.id])
);

export function profileForSource(source) {
  return SOURCE_TO_PROFILE[String(source).toLowerCase()] || "canon";
}
